/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as LexRouteImport } from './routes/lex'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EscritorioRouteImport } from './routes/escritorio'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNewsRouteImport } from './routes/api.news'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const LexRoute = LexRouteImport.update({
  id: '/lex',
  path: '/lex',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioRoute = EscritorioRouteImport.update({
  id: '/escritorio',
  path: '/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/escritorio': typeof EscritorioRoute
  '/insights': typeof InsightsRoute
  '/lex': typeof LexRoute
  '/resultados': typeof ResultadosRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/escritorio': typeof EscritorioRoute
  '/insights': typeof InsightsRoute
  '/lex': typeof LexRoute
  '/resultados': typeof ResultadosRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/escritorio': typeof EscritorioRoute
  '/insights': typeof InsightsRoute
  '/lex': typeof LexRoute
  '/resultados': typeof ResultadosRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/escritorio'
    | '/insights'
    | '/lex'
    | '/resultados'
    | '/api/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/escritorio'
    | '/insights'
    | '/lex'
    | '/resultados'
    | '/api/news'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/escritorio'
    | '/insights'
    | '/lex'
    | '/resultados'
    | '/api/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  EscritorioRoute: typeof EscritorioRoute
  InsightsRoute: typeof InsightsRoute
  LexRoute: typeof LexRoute
  ResultadosRoute: typeof ResultadosRoute
  ApiNewsRoute: typeof ApiNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lex': {
      id: '/lex'
      path: '/lex'
      fullPath: '/lex'
      preLoaderRoute: typeof LexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio': {
      id: '/escritorio'
      path: '/escritorio'
      fullPath: '/escritorio'
      preLoaderRoute: typeof EscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  EscritorioRoute: EscritorioRoute,
  InsightsRoute: InsightsRoute,
  LexRoute: LexRoute,
  ResultadosRoute: ResultadosRoute,
  ApiNewsRoute: ApiNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
