/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LexRouteImport } from './routes/lex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNewsRouteImport } from './routes/api.news'

const LexRoute = LexRouteImport.update({
  id: '/lex',
  path: '/lex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lex': typeof LexRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lex': typeof LexRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lex': typeof LexRoute
  '/api/news': typeof ApiNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lex' | '/api/news'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lex' | '/api/news'
  id: '__root__' | '/' | '/lex' | '/api/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LexRoute: typeof LexRoute
  ApiNewsRoute: typeof ApiNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lex': {
      id: '/lex'
      path: '/lex'
      fullPath: '/lex'
      preLoaderRoute: typeof LexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LexRoute: LexRoute,
  ApiNewsRoute: ApiNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
